### ISSUE TITLE
与datetimepicker连用验证datetime会出现bug

### ISSUE THREAD

**Issue by preinoch** [1029131145/vali#7]
在使用datetimepicker选取时间的过程中会失去文本框焦点，导致误判断

**Comment by 1029131145** [comment]
日期格式：1996-09-24 or 1996-9-24 or 1996/5/21 
错误格式：1996-2-30 
time="t" 验证时间 10:10:10 
datetime="t" 验证日期时间 1996-09-24 10:10:10  

格式：1996-09-24 10:10:10  

看看格式是否正确。(_^__^_) 嘻嘻

**Comment by preinoch** [comment]
@1029131145 可能你误会了，不是验证格式时候出错，是触发验证的事件节点是有问题的，在使用datetimepicker([https://github.com/flavienlaurent/datetimepicker](url))获取datetime过程中，文本框会失去焦点，但这时value并没有被获取，所以这时候使用change事件来判断格式相对合适，我本地已经加上change事件，解决这个问题。这个应该不算bug。
